#!/bin/bash
#PBS -l select=1:ncpus=1
#PBS -l walltime=99999:00:00
#PBS -N rsync
#PBS -j oe
#PBS -m ae
#PBS -M kprovost@amnh.org
#PBS -k oe

# change to the working directory
#cd $PBS_O_WORKDIR
#echo "pbsworkdir"
#echo $PBS_O_WORKDIR
#EXECDIR=`pwd`
#export PATH=./:$PATH
#echo $PATH

cd /home/kprovost/nas2/Analysis_SLiM/FINISHED_SCALED/VCFS/

rsync -avzP *vcf ~/nas4/Analysis_SLiM/FINISHED_SCALED/VCFS/

cd /vz-nas2-archive/SLiM_Pipeline-Archive/FINISHED_SCALED/

rsync -avzP VCFS/*vcf ~/nas4/Analysis_SLiM/FINISHED_SCALED/VCFS/