bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA06.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA07.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB07.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB11.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC01.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD02.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD07.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD11.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE08.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WF02.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WF03.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WF05.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WG05.merged.realigned.bam
bellii	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH08.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WA01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WB01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WC01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WD01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WE01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WA07.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WB05.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WD03.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WD05.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WE01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WE02.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WF01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WF02.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WG01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WG06.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA01.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA03.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE05.merged.realigned.bam
bilineata	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WG09.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WA02.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WB02.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WF01.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WG01.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WH01.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WE03.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WE06.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WF04.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB08.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC08.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC09.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD03.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD08.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD09.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WF09.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WG02.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WG08.merged.realigned.bam
brunneicapillus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH02.merged.realigned.bam
crissale	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA09.merged.realigned.bam
crissale	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB06.merged.realigned.bam
crissale	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC06.merged.realigned.bam
crissale	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE10.merged.realigned.bam
crissale	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH05.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WB04.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WC06.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WD02.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WF06.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WG02.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WH06.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA12.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC02.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD10.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE06.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WF10.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WG03.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WG10.merged.realigned.bam
curvirostre	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH10.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA02.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA08.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB01.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB02.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB05.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC11.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD01.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD06.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE02.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE03.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WF01.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WG01.merged.realigned.bam
flaviceps	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH01.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WC02.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WD02.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WE02.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WF02.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WG02.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA05.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA11.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WF06.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WF08.merged.realigned.bam
fusca	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WG06.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WA01.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WA02.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WA04.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WB02.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WB03.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WC05.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WD04.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WE04.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WG03.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WH03.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB03.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB10.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC03.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC10.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE01.merged.realigned.bam
melanura	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH09.merged.realigned.bam
nitens	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA04.merged.realigned.bam
nitens	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC05.merged.realigned.bam
nitens	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WD05.merged.realigned.bam
nitens	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE07.merged.realigned.bam
nitens	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH03.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WA03.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WB03.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WC03.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WD03.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245107_P01_WH02.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WA05.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WA06.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WC02.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WC03.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WD01.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WD06.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WF03.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245109_P002_WH01.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WA10.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WB09.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WC07.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WE09.merged.realigned.bam
sinuatus	/vz-nas1-active/ProcessedGenomicReads/EVERY_PLATE/ANGSD/REALIGNED_BAMS/AMN_245111_P002_WH06.merged.realigned.bam
